### PR TITLE
Plugin selection to install

### LINKED ISSUE #9: Plugin Selection / Section by Required / Recommended
Hi,

I have couple of required plugin and rest of them are recommended plugins. But Merlin is installing them all in my opinion.

There should be headings for required and recommended plugins and also selection for what plugins we want to install.

Thanks

### PR DESCRIPTION
**Pull request by meshakeeb**
Fixes #9

### CODE REVIEW

**Comment by meshakeeb** [comment]
Hello @richtabor 

Waiting for your feedback on the PR.

Thanks

**Comment by richtabor** [comment]
I like where it's headed. What do you think about having them selected by default (checkmarked) instead? 

Currently, if the plugins are not selected and the user does not open the drawer to select them, the wizard shows the green checkmark when "Install" is clicked. That signifies the plugins have been successfully installed — although they have not been.

Make sense?

**Comment by meshakeeb** [comment]
Hi,

Working on it and also changing the style to the content importer list you have already done. And working on adding classes and text according to the steps.

image

Thanks

**Comment by richtabor** [comment]
Ok cool. What about if we used the same current green/yellow/red checkmarks as in the content importer?

**Comment by meshakeeb** [comment]
Hi,

I tried that but your processing functionality is adding classes on the right time i.e like adding classes in the second trip not the first one.

```
$current_node = $(this);
$current_node.removeClass('installing error success').addClass('installing');
$current_node.find("i").removeClass('installing error success').addClass('installing');
```
and 

```
$current_node.find("span").text("failed").removeClass('installing error success').addClass('error');
$current_node.find("i").removeClass('installing error success').addClass('error');
```

This functionality need to be refactored with better code and response from server.

Thanks

**Comment by meshakeeb** [comment]
I am pushing changes for the plugin selection please have a look its working this way and also we need to test for plugins which redirect to welcome page i.e. bbpress, woocommerce.

image

Thanks

**Pull request closed without merging**
