### PR TITLE
Fixed textdomain

### PR DESCRIPTION
**Pull request by vlthemes**

### CODE REVIEW

**Comment by richtabor** [comment]
I'm going to go ahead and push a commit to with these changes. 👍

**Comment by vlthemes** [comment]
As a reviewer on TF you can approve work with such errors? How can they be explained in case of reject or how best to proceed?

P.S. wordpress-importer domain still here

Screenshot:
http://take.ms/yLiQO

**Comment by vlthemes** [comment]
Reviewer (pasqualevitiello) said

http://take.ms/4cjhq

**Comment by richtabor** [comment]
@vlthemes Please note that Merlin WP **is still very much in production** and being committed to nearly every day now. We're working to resolve bigger (and much more important) issues first, but aim to have these smaller issues (such as text domains and Theme Check validity) knocked out _eventually_.

You're more than welcome to send PR's with suggested changes to reflect the Theme Check issues, but right now, we're focused on getting the project working 100%, then we'll tweak little issues that have no real affect on the goal of Merlin WP.

**Pull request closed without merging**
