### PR TITLE
Add Content Import Progress Bar 🎉

### PR DESCRIPTION
**Pull request by richtabor**
As recorded in #55.

### CODE REVIEW

**Comment by capuderg** [comment]
Hi @richtabor I've looked at the PR and tested it locally. The demo import progress looks good, but I have a question...

Why did  you change some JS code for `PluginManager` in this commit: https://github.com/richtabor/MerlinWP/pull/109/commits/2651c6fde7dd6487006c732bd38b603014a14736 ?

Some of these JS code changes (those made in PluginManager part) should not be in this PR.

I've also tidied up some JS code you added to the progress bar part in my last commit.

**Comment by capuderg** [comment]
I've also tested the plugin install/activation in this branch and it's not working properly (all plugins get installed, even, if you uncheck some). This is because of the JS code that was changed in the above mentioned commit.

**Comment by richtabor** [comment]
I'll double-check. I thought I only changed the text span that was incorrectly replacing the plugin's name with the added class (which changes the checkmark icon color).

**Comment by capuderg** [comment]
Yes, please do. Let me know, once it's ready, for the second review.

**Comment by richtabor** [comment]
@capuderg I reverted the changes that caused the issue in the first place. I'm not sure if I'm missing any changes that were added in-betweenm but it seems to be working as expected now. 👍

**Comment by richtabor** [comment]
Agreed - it's def a bit messy currently.. but it works! 😬

**Comment by contempoinc** [comment]
Whens this going to be merged and pushed to the "dist" folder? Is it ready to go?

**Pull request merged**
