### PR TITLE
basic multi-demo select box CSS fix

### PR DESCRIPTION
**Pull request by JiveDig**
Temporary styling fix for https://github.com/richtabor/MerlinWP/issues/49 so it can launch.

screen shot 2018-10-03 at 2 10 46 pm

### CODE REVIEW

**Comment by richtabor** [comment]
Hey man! I've pushed the minor style updates I started on earlier. As you mentioned, this will suffice for now. I think it'd be neat to have a demo image/preview somehow - but that's quite a UX issue for such a small window. 

I also don't use multi-demos myself for any of my themes, so it's not really on my personal priority list. 

Here's a screenshot:

screen shot 2018-10-04 at 6 24 04 pm

What do you think?

**Comment by JiveDig** [comment]
Yeah, this is awesome (for now). My main usage is multi-demo so I can help with preview images later on, but pretty sure everyone agrees it's not a deal breaker right now.

Just gotta minify your CSS first ;)

**Comment by JiveDig** [comment]
Or maybe i don't know PR's enough, do I need to bring in your changes and minify or whatever?

**Comment by JiveDig** [comment]
Maybe I did something wrong... but this is what I see Mac/Chrome (no caret/icon):
screen shot 2018-10-04 at 9 49 02 pm

**Comment by JiveDig** [comment]
Wow nevermind, totally missed updating the svg/sprite. Looks great!

**Comment by JiveDig** [comment]
"pretty sure" i fixed that conflict. ;)

**Comment by JiveDig** [comment]
Oh wait, you merged your changes earlier. I see. Closing this.

**Pull request closed without merging**
